# Changes here will be overwritten by Copier
_commit: v2.1.13
_src_path: harmon-stack
ansible: true
bunch_add: true
ci_cd: github_actions
code_templates: false
data_folder: false
design_files: false
devcontainer: false
git_init: true
github_collaboration_templates: true
github_release_init: true
github_remote_create: true
infra: []
license: mit
observability: []
obsidian_project_add: false
project_description: This is a test project
project_name: Test Project
project_slug: test-project
project_type: code
project_url: https://projecturl.com
run_task_bootstrap: false
run_task_install: false
